model:
  name: resnet_cnn

hyperparams:
  epochs: 50
  batch_size: 256
  lr: 0.0001
  step_size: 10
  gamma: 0.35
  use_cuda: True
  val_every: 5

pairwise_confusion:
  pc_loss: False
  lambda_pc: 0.15
  lambda_ec: 0.03

dataset:
  name: plant_seedlings
